'use client';

import { ShoppingBag, X } from 'lucide-react';
import { useState } from 'react';

type Product = { id: string; name: string; description: string | null; price: number; currency: string; image_url: string | null; payment_link: string | null };
type PaymentOptions = { methods?: Array<{ provider: string; label: string; instructions?: string; enabled?: boolean }>; checkout_fields?: Array<{ key: string; label: string; required?: boolean }> };

export function ProductCollection({ products, primary, radius, grid, workspaceId, paymentOptions }: { products: Product[]; primary: string; radius: string; grid: boolean; workspaceId: string; paymentOptions: PaymentOptions }) {
  const [cart, setCart] = useState<Product[]>([]);
  const [open, setOpen] = useState(false);
  const [checkout, setCheckout] = useState(false);
  const [receiptUrl, setReceiptUrl] = useState('');
  const [uploading, setUploading] = useState(false);
  const [notice, setNotice] = useState('');
  const [form, setForm] = useState({ name: '', email: '', location: '', paymentMethod: '', customFields: {} as Record<string, string> });
  const methods = (paymentOptions.methods ?? []).filter((method) => method.enabled !== false);
  const fields = paymentOptions.checkout_fields ?? [];
  const total = cart.reduce((sum, item) => sum + item.price, 0);

  function add(product: Product) { setCart((items) => items.some((item) => item.id === product.id) ? items : [...items, product]); }
  async function uploadReceipt(file: File) { setUploading(true); const data = new FormData(); data.set('workspaceId', workspaceId); data.set('file', file); const response = await fetch('/api/checkout/receipt', { method: 'POST', body: data }); const result = await response.json(); setNotice(response.ok ? 'Receipt uploaded.' : result.error ?? 'Receipt upload failed.'); if (response.ok) setReceiptUrl(result.url); setUploading(false); }
  async function submit() { const response = await fetch('/api/checkout/business', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ workspaceId, items: cart.map((item) => ({ id: item.id, type: 'product', quantity: 1 })), receiptUrl, ...form }) }); const result = await response.json(); setNotice(response.ok ? result.message : result.error ?? 'Checkout failed.'); if (response.ok) { setCart([]); setCheckout(false); } }

  return <>
    <section className={`mt-8 ${grid ? 'grid grid-cols-2 gap-3 sm:grid-cols-3' : 'space-y-3'}`}>{products.map((product) => <div key={product.id} className="overflow-hidden border" style={{ borderColor: `${primary}55`, background: `${primary}12`, borderRadius: radius }}>{product.image_url && <img src={product.image_url} alt="" className="h-28 w-full object-cover" />}<div className="p-3"><p className="text-xs font-semibold">{product.name}</p><p className="mt-1 text-[10px] text-white/55">{product.description}</p><p className="mt-2 text-xs font-bold" style={{ color: primary }}>{product.currency} {product.price}</p><button onClick={() => product.payment_link ? window.open(product.payment_link, '_blank', 'noopener,noreferrer') : add(product)} className="mt-3 flex w-full items-center justify-center gap-1 rounded-lg py-2 text-[10px] font-bold text-black" style={{ background: primary }}><ShoppingBag className="h-3 w-3" /> {product.payment_link ? 'Pay now' : 'Add to cart'}</button></div></div>)}</section>
    {cart.length > 0 && <button onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-30 flex items-center gap-2 rounded-full px-4 py-3 text-xs font-bold text-black shadow-xl" style={{ background: primary }}><ShoppingBag className="h-4 w-4" /> Cart ({cart.length})</button>}
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="max-h-[90vh] w-full max-w-md overflow-y-auto rounded-2xl border border-white/10 bg-[#0b1620] p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-white">{checkout ? 'Checkout' : 'Your cart'}</h2><button onClick={() => setOpen(false)}><X className="h-4 w-4 text-white/50" /></button></div><div className="mt-4 space-y-2">{cart.map((item) => <div key={item.id} className="flex justify-between rounded-lg bg-white/5 p-3 text-xs text-white"><span>{item.name}</span><span>{item.currency} {item.price}</span></div>)}</div>{!checkout ? <><p className="mt-4 text-right text-sm font-bold text-white">Total: {cart[0]?.currency} {total}</p><button onClick={() => setCheckout(true)} className="mt-4 w-full rounded-lg py-2.5 text-xs font-bold text-black" style={{ background: primary }}>Continue to checkout</button></> : <div className="mt-4 space-y-3"><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Full name" className="field" /><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="Email address" className="field" /><input value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} placeholder="Location" className="field" />{fields.map((field) => <input key={field.key} required={field.required} value={form.customFields[field.key] ?? ''} onChange={(event) => setForm({ ...form, customFields: { ...form.customFields, [field.key]: event.target.value } })} placeholder={field.label} className="field" />)}<select value={form.paymentMethod} onChange={(event) => setForm({ ...form, paymentMethod: event.target.value })} className="field"><option value="">Choose payment method</option>{methods.map((method) => <option key={method.provider} value={method.provider}>{method.label || method.provider}</option>)}</select>{methods.find((method) => method.provider === form.paymentMethod)?.instructions && <p className="rounded-lg bg-white/5 p-3 text-[10px] text-white/60">{methods.find((method) => method.provider === form.paymentMethod)?.instructions}</p>}<label className="block text-[10px] text-white/60">Transaction receipt<input type="file" accept="image/*,application/pdf" disabled={uploading} onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadReceipt(file); }} className="field mt-1" /></label>{notice && <p className="text-[10px] text-cyan-300">{notice}</p>}<button onClick={submit} disabled={!form.name || !form.email || !form.paymentMethod} className="w-full rounded-lg py-2.5 text-xs font-bold text-black disabled:opacity-40" style={{ background: primary }}>Submit order for review</button></div>}</div></div>}
  </>;
}
