'use client';

import { useState, useTransition } from 'react';
import { Check, Eye, ImagePlus, Link2, Palette, Plus, Save, Sparkles, Trash2, X } from 'lucide-react';
import { updateSabiBioSettings, uploadSabiBioMedia } from '@/app/(dashboard)/dashboard/[workspace_id]/sabibio/actions';
import { DEFAULT_SABIBIO_BRANDING, getTemplateLogoDefaults, SABIBIO_TEMPLATES, type SabiBioLink } from '@/lib/sabibio/templates';
import { SabiBioPreview } from './SabiBioPreview';

type Product = { id: string; name: string; price: number; currency: string; image_url: string | null };
type Config = { id: string; name: string; slug: string; sabibio_enabled: boolean; sabibio_template_id: string; sabibio_branding: Record<string, any>; sabibio_links: SabiBioLink[]; sabibio_channels: Record<string, any>; sabibio_socials: Record<string, string>; sabibio_products: string[]; sabibio_legal: Record<string, any> };
const tabNames = ['templates', 'branding', 'links', 'channels', 'products', 'legal', 'preview'] as const;
type Tab = typeof tabNames[number];

export function SabiBioBuilder({ workspace, products, initialConfig }: { workspace: { id: string; name: string }; products: Product[]; initialConfig: Config }) {
  const [config, setConfig] = useState(initialConfig);
  const [tab, setTab] = useState<Tab>('templates');
  const [editingLink, setEditingLink] = useState<SabiBioLink | null>(null);
  const [pending, startTransition] = useTransition();
  const [notice, setNotice] = useState('');
  const patch = (value: Partial<Config>) => setConfig((current) => ({ ...current, ...value }));
  const patchBranding = (key: string, value: unknown) => patch({ sabibio_branding: { ...config.sabibio_branding, [key]: value } });
  const patchChannel = (key: string, value: unknown) => patch({ sabibio_channels: { ...config.sabibio_channels, [key]: value } });
  const save = () => { const form = new FormData(); for (const [key, value] of [['template_id', config.sabibio_template_id], ['enabled', String(config.sabibio_enabled)], ['slug', config.slug], ['branding', JSON.stringify(config.sabibio_branding)], ['links', JSON.stringify(config.sabibio_links)], ['channels', JSON.stringify(config.sabibio_channels)], ['socials', JSON.stringify(config.sabibio_socials)], ['products', JSON.stringify(config.sabibio_products)], ['legal', JSON.stringify(config.sabibio_legal)]]) form.set(key, value); startTransition(async () => { const result = await updateSabiBioSettings(workspace.id, form); setNotice(result.error ?? 'Saved successfully.'); }); };
  const selectTemplate = (id: string) => { const template = SABIBIO_TEMPLATES.find((item) => item.id === id) ?? SABIBIO_TEMPLATES[0]; const logo = getTemplateLogoDefaults(id); patch({ sabibio_template_id: id, sabibio_branding: { ...DEFAULT_SABIBIO_BRANDING, ...config.sabibio_branding, primary_color: template.primary, background_color: template.background, accent_color: template.accent, font_family: template.font, logo_shape: logo.shape, logo_position: logo.position, cover_overlap: logo.overlap } }); };
  const preview = { name: config.name, slug: config.slug, templateId: config.sabibio_template_id, enabled: config.sabibio_enabled, branding: config.sabibio_branding, links: config.sabibio_links, channels: config.sabibio_channels, socials: config.sabibio_socials, products: products.filter((product) => config.sabibio_products.includes(product.id)) };
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-cyan-400" /><h1 className="text-xl font-semibold text-white">SabiBio Page Builder</h1></div><p className="mt-1 text-xs text-gray-500">Create a public page for {workspace.name}.</p></div><button onClick={save} disabled={pending} className="flex items-center gap-2 rounded-lg bg-linear-to-r from-cyan-400 to-blue-500 px-4 py-2 text-xs font-bold text-slate-950 disabled:opacity-50"><Save className="h-3.5 w-3.5" />{pending ? 'Saving...' : 'Save Page'}</button></div>{notice && <p className="rounded-lg border border-cyan-500/30 bg-cyan-500/10 p-3 text-xs text-cyan-300">{notice}</p>}<div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><div className="overflow-hidden rounded-2xl border border-white/10 bg-zinc-900/50"><div className="flex gap-1 overflow-x-auto border-b border-white/10 p-2">{tabNames.map((name) => <button key={name} onClick={() => setTab(name)} className={`rounded-lg px-3 py-2 text-xs capitalize ${tab === name ? 'bg-cyan-400/10 text-cyan-300' : 'text-gray-500 hover:bg-white/5 hover:text-white'}`}>{name}</button>)}</div><div className="p-5">{tab === 'templates' && <Templates selected={config.sabibio_template_id} select={selectTemplate} />}{tab === 'branding' && <Branding config={config} patch={patch} patchBranding={patchBranding} />}{tab === 'links' && <Links links={config.sabibio_links} edit={setEditingLink} remove={(id) => patch({ sabibio_links: config.sabibio_links.filter((link) => link.id !== id) })} toggle={(id) => patch({ sabibio_links: config.sabibio_links.map((link) => link.id === id ? { ...link, active: !link.active } : link) })} />}{tab === 'channels' && <Channels config={config} patch={patch} patchChannel={patchChannel} />}{tab === 'products' && <Products products={products} selected={config.sabibio_products} change={(ids) => patch({ sabibio_products: ids })} />}{tab === 'legal' && <Legal legal={config.sabibio_legal} change={(key, value) => patch({ sabibio_legal: { ...config.sabibio_legal, [key]: value } })} />}{tab === 'preview' && <div className="flex justify-center"><SabiBioPreview config={preview} /></div>}</div></div><div className="hidden rounded-2xl border border-white/10 bg-zinc-900/30 p-4 xl:block"><p className="mb-3 text-[10px] uppercase tracking-wider text-gray-500">Live preview</p><SabiBioPreview config={preview} /></div></div>{editingLink && <LinkModal link={editingLink} cancel={() => setEditingLink(null)} save={(link) => { const exists = config.sabibio_links.some((item) => item.id === link.id); patch({ sabibio_links: exists ? config.sabibio_links.map((item) => item.id === link.id ? link : item) : [...config.sabibio_links, link] }); setEditingLink(null); }} />}</div>;
}

function Templates({ selected, select }: { selected: string; select: (id: string) => void }) { return <div><h2 className="text-sm font-semibold text-white">Templates</h2><p className="mt-1 text-xs text-gray-500">Each preset changes color, typography, spacing, radius, shadow and composition.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{SABIBIO_TEMPLATES.map((template) => <button key={template.id} onClick={() => select(template.id)} className={`rounded-xl border p-3 text-left ${selected === template.id ? 'border-cyan-400/60 bg-cyan-400/10' : 'border-white/10 bg-black/10'}`}><div className="mb-3 h-16 rounded-lg p-3" style={{ background: template.background, boxShadow: template.shadow }}><div className="h-2 w-16 rounded-full" style={{ background: template.primary }} /><div className="mt-2 h-2 w-24 rounded-full bg-white/20" /><div className="mt-3 h-5 rounded" style={{ background: `${template.accent}99` }} /></div><span className="text-xs font-semibold text-white">{template.name}</span><p className="mt-1 text-[10px] text-gray-500">{template.category}</p>{selected === template.id && <Check className="mt-2 h-3.5 w-3.5 text-cyan-300" />}</button>)}</div></div>; }

function Branding({ config, patch, patchBranding }: { config: Config; patch: (value: Partial<Config>) => void; patchBranding: (key: string, value: unknown) => void }) { const [uploading, setUploading] = useState(false); async function upload(file: File, key: string) { setUploading(true); const form = new FormData(); form.set('file', file); const result = await uploadSabiBioMedia(config.id, form); if (result.url) patchBranding(key, result.url); setUploading(false); } return <div className="max-w-xl space-y-4"><h2 className="text-sm font-semibold text-white">Profile & branding</h2><input value={config.slug} onChange={(event) => patch({ slug: event.target.value })} placeholder="Public slug" className="field" /><textarea value={String(config.sabibio_branding.bio ?? '')} onChange={(event) => patchBranding('bio', event.target.value)} placeholder="Bio / tagline" rows={3} className="field resize-none" /><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">Logo</span><input type="file" accept="image/*" disabled={uploading} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file, 'avatar_url'); }} className="field" /></label><label><span className="label">Cover image</span><input type="file" accept="image/*" disabled={uploading} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file, 'cover_url'); }} className="field" /></label></div><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">Logo shape</span><select value={String(config.sabibio_branding.logo_shape ?? 'circle')} onChange={(event) => patchBranding('logo_shape', event.target.value)} className="field"><option value="circle">Circle</option><option value="square">Square</option><option value="rounded">Rounded</option></select></label><label><span className="label">Logo position</span><select value={String(config.sabibio_branding.logo_position ?? 'center')} onChange={(event) => patchBranding('logo_position', event.target.value)} className="field"><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option><option value="cover-overlap">Cover overlap</option></select></label></div>{[['primary_color', 'Primary'], ['background_color', 'Background'], ['accent_color', 'Accent']].map(([key, label]) => <label key={key}><span className="label">{label}</span><input type="color" value={String(config.sabibio_branding[key] ?? '#06b6d4')} onChange={(event) => patchBranding(key, event.target.value)} className="h-9 w-full rounded bg-transparent" /></label>)}<label className="flex items-center justify-between rounded-xl border border-white/10 p-3"><span className="text-xs text-white">Publish page</span><input type="checkbox" checked={config.sabibio_enabled} onChange={(event) => patch({ sabibio_enabled: event.target.checked })} className="h-4 w-4 accent-cyan-400" /></label></div>; }

function Links({ links, edit, remove, toggle }: { links: SabiBioLink[]; edit: (link: SabiBioLink) => void; remove: (id: string) => void; toggle: (id: string) => void }) { return <div><button onClick={() => edit({ id: crypto.randomUUID(), title: '', url: '', icon: '↗', category: 'General', active: true, is_featured: false })} className="mb-4 flex items-center gap-2 rounded-lg bg-cyan-400 px-3 py-2 text-xs font-bold text-slate-950"><Plus className="h-3.5 w-3.5" /> Add link</button><div className="space-y-2">{links.map((link) => <div key={link.id} className="flex items-center gap-3 rounded-xl border border-white/10 p-3"><span className="flex-1 text-xs text-white">{link.icon} {link.title || 'Untitled'}</span><button onClick={() => toggle(link.id)} className="text-[10px] text-gray-500">{link.active ? 'Hide' : 'Show'}</button><button onClick={() => edit(link)} className="text-[10px] text-cyan-300">Edit</button><button onClick={() => remove(link.id)} className="text-gray-500"><Trash2 className="h-3.5 w-3.5" /></button></div>)}</div></div>; }

function Channels({ config, patch, patchChannel }: { config: Config; patch: (value: Partial<Config>) => void; patchChannel: (key: string, value: unknown) => void }) { const socials = ['instagram', 'tiktok', 'youtube', 'x', 'linkedin', 'facebook']; return <div className="space-y-4"><h2 className="text-sm font-semibold text-white">Channels & socials</h2>{[['web_chat_enabled', 'Web chat'], ['whatsapp_enabled', 'WhatsApp'], ['telegram_enabled', 'Telegram']].map(([key, label]) => <label key={key} className="flex items-center justify-between rounded-xl border border-white/10 p-3"><span className="text-xs text-white">{label}</span><input type="checkbox" checked={Boolean(config.sabibio_channels[key])} onChange={(event) => patchChannel(key, event.target.checked)} className="h-4 w-4 accent-cyan-400" /></label>)}<div className="grid gap-3 sm:grid-cols-2"><input value={String(config.sabibio_channels.whatsapp_number ?? '')} onChange={(event) => patchChannel('whatsapp_number', event.target.value)} placeholder="WhatsApp number" className="field" /><input value={String(config.sabibio_channels.telegram_username ?? '')} onChange={(event) => patchChannel('telegram_username', event.target.value.replace(/^@/, ''))} placeholder="Telegram username" className="field" /></div><div className="grid gap-3 sm:grid-cols-2">{socials.map((key) => <input key={key} value={config.sabibio_socials[key] ?? ''} onChange={(event) => patch({ sabibio_socials: { ...config.sabibio_socials, [key]: event.target.value } })} placeholder={`${key} URL or handle`} className="field" />)}</div><textarea value={String(config.sabibio_channels.default_welcome_msg ?? '')} onChange={(event) => patchChannel('default_welcome_msg', event.target.value)} placeholder="Welcome message" rows={3} className="field resize-none" /></div>; }

function Products({ products, selected, change }: { products: Product[]; selected: string[]; change: (ids: string[]) => void }) { return <div><h2 className="text-sm font-semibold text-white">Products on SabiBio</h2><div className="mt-4 space-y-2">{products.map((product) => <label key={product.id} className="flex items-center gap-3 rounded-xl border border-white/10 p-3"><input type="checkbox" checked={selected.includes(product.id)} onChange={() => change(selected.includes(product.id) ? selected.filter((id) => id !== product.id) : [...selected, product.id])} className="h-4 w-4 accent-cyan-400" />{product.image_url && <img src={product.image_url} alt="" className="h-8 w-8 rounded object-cover" />}<span className="text-xs text-white">{product.name} · {product.currency} {product.price}</span></label>)}</div></div>; }

function Legal({ legal, change }: { legal: Record<string, any>; change: (key: string, value: unknown) => void }) { return <div className="space-y-4"><h2 className="text-sm font-semibold text-white">Legal footer pages</h2>{['privacy_policy', 'terms_of_service', 'disclaimer', 'cookie_policy'].map((key) => <textarea key={key} value={String(legal[key] ?? '')} onChange={(event) => change(key, event.target.value)} placeholder={key.replaceAll('_', ' ')} rows={4} className="field resize-none" />)}<label className="flex items-center gap-2 text-xs text-gray-400"><input type="checkbox" checked={Boolean(legal.cookie_consent_required)} onChange={(event) => change('cookie_consent_required', event.target.checked)} className="h-4 w-4 accent-cyan-400" /> Require cookie consent</label></div>; }

function LinkModal({ link, cancel, save }: { link: SabiBioLink; cancel: () => void; save: (link: SabiBioLink) => void }) { const [draft, setDraft] = useState(link); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-zinc-900 p-5"><div className="mb-4 flex justify-between"><h2 className="text-sm font-semibold text-white">Edit link</h2><button onClick={cancel}><X className="h-4 w-4 text-gray-500" /></button></div><div className="space-y-3"><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Title" className="field" /><input value={draft.url} onChange={(event) => setDraft({ ...draft, url: event.target.value })} placeholder="URL" className="field" /><input value={draft.icon} onChange={(event) => setDraft({ ...draft, icon: event.target.value })} placeholder="Icon" className="field" /><label className="flex items-center gap-2 text-xs text-gray-400"><input type="checkbox" checked={draft.is_featured} onChange={(event) => setDraft({ ...draft, is_featured: event.target.checked })} className="accent-cyan-400" /> Featured</label></div><button onClick={() => save(draft)} className="mt-5 rounded-lg bg-cyan-400 px-4 py-2 text-xs font-bold text-slate-950">Save link</button></div></div>; }
